{% set name = "neuralprophet" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  # Unsatisfiable dependencies on s390x
  # No poetry for py312
  skip: true  # [py<39 or py>311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

source:
  url: https://github.com/ourownstory/neural_prophet/archive/refs/tags/{{ version }}.tar.gz
  sha256: fc9490ac42f878524669189482368c82243d7138a078cebdf1ae3f5d76de2414

requirements:
  host:
    - pip
    - python
    - poetry
    - wheel
  run:
    - python
    - nbformat >=5.8.0,<6.0.0
    - numpy >=1.25.0,<2.0.0
    - pandas >=2.0.0,<3.0.0
    - matplotlib-base >=3.5.3,<4.0.0
    - pytorch >=2.0.0,<3.0.0
    - torchmetrics >=1.0.0,<2.0.0
    - holidays >=0.41
    - typing_extensions >=4.5.0,<5.0.0
    - plotly >=5.13.1,<6.0.0
    - pytorch-lightning >=1.9.4,<2.0.0
    - tensorboard >=2.11.2,<3.0.0
    - captum >=0.6.0

test:
  imports:
    - neuralprophet
  source_files:
    - tests/
  requires:
    - pip
    - pytest
    - ipython
    # Although, technically, an extra == "plotly-resampler" the tests
    # requiring it are run anyway
    - plotly-resampler
    # one test, tests/test_plotting.py::test_plot[plotly-static], requires
    - python-kaleido
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://neuralprophet.com/
  summary: NeuralProphet is an easy to learn framework for interpretable time series forecasting
  description: |
    NeuralProphet is an easy to learn framework for interpretable time
    series forecasting. NeuralProphet is built on PyTorch and combines
    Neural Networks and traditional time-series algorithms, inspired
    by Facebook Prophet and AR-Net.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ourownstory/neural_prophet
  doc_url: https://neuralprophet.com/contents.html
