{% set name = "neuralprophet" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: true  # [py<36 or win32 or s390x]
  script: {{ PYTHON }} -m pip install . -vv

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neuralprophet-{{ version }}.tar.gz
  sha256: 7df64ae1243c33b6434e993b56e9712fa7cf4b6dcb00958dd309b331fa193bde
  patches:
    - fix_scripts.patch

requirements:
  host:
    - m2-patch  # [win] 
    - patch     # [not win]
    - pip
    - python
    - setuptools
    - wheel
  run:
    - convertdate >=2.1.2
    - dataclasses >=0.6
    - holidays >=0.11.3.1
    - ipywidgets >=7.5.1
    - lunarcalendar >=0.0.9
    - matplotlib-base >=2.0.0
    - numpy >=1.15.4
    - pandas >=1.0.4
    - python
    - python-dateutil >=2.8.0
    - pytorch >=1.4.0
    - torch-lr-finder >=0.2.1
    - tqdm >=4.50.2

test:
  imports:
    - neuralprophet
  commands:
    # neuralprophet 0.3.2 requires dataclasses, which is not installed.
    # but dataclasses 0.8 is available.
    #- pip check
  requires:
    - pip

about:
  home: https://neuralprophet.com/
  summary: Explainable Forecasting at Scale
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ourownstory/neural_prophet
  doc_url: https://neuralprophet.com/html/contents.html